### ISSUE TITLE
feature request: sync between clouds

### ISSUE THREAD

**Issue by demios97** [x0b/rcloneExplorer#30]
Can you add an option to sync between two clouds?

**Comment by x0b** [comment]
Could you stop spamming the repos with this?

You have already asked in the upstream repo (https://github.com/kaczmarkiewiczp/rcloneExplorer/issues/239) and in multiple pull requests (https://github.com/x0b/rcloneExplorer/pull/29, https://github.com/kaczmarkiewiczp/rcloneExplorer/pull/252)
