### ISSUE TITLE
Make Thumbnail Filesize limit user configurable

### ISSUE THREAD

**Issue by moarbytes** [x0b/rcloneExplorer#31]
Are thumbnails set to only show for files under a certain size? I'm unable to get them to display for anything larger than ~15MB? I looked at `app/src/main/java/ca/pkay/rcloneexplorer/Services/ThumbnailsLoadingService.java`, but that didn't seem to set any sort of file size limitation that I could ascertain.

**Comment by x0b** [comment]
There is a 20MB limit IIRC. Is this too high/too low?

**Comment by moarbytes** [comment]
Personally I'd like it set to 1GiB or larger, but that would likely be far to high for folks with a high speed connection. Is it possible to make it a user configurable setting? If not, and 1GiB is too high of a default, if you'd point me to where the setting is in the code I'd be fine with building from source. :)

**Comment by x0b** [comment]
The limit is [located in a RecyclerView](https://github.com/x0b/rcloneExplorer/blob/fab5181e59e859b67217ab74afe6cdfa0e573ecd/app/src/main/java/ca/pkay/rcloneexplorer/RecyclerViewAdapters/FileExplorerRecyclerViewAdapter.java#L102).

I'll add this as setting for the next feature release.

**Comment by x0b** [comment]
It is now available in the current preview: https://github.com/x0b/rcloneExplorer/releases/tag/v1.10.0-pre1

**Comment by moarbytes** [comment]
Successfully loaded thumbnails via SSH and Google Drive mounts for files up to 2000MiB over WiFi. 

One possible bug - even though the thumbnail image size doesn't change within the app (at least on my s10e), if I rotate the screen the app "loses" the thumbnails until I exit and re-enter the directory.

**Comment by x0b** [comment]
I have looked into this issue and have opened a new one since it is not related. 

I discovered that the bug prevents thumbnails from being cached correctly. Setting a high thumbnail size limit can therefore lead to high amounts of data download just for thumbnails until this is fixed.
