### ISSUE TITLE
HTTP Proxy support

### ISSUE THREAD

**Issue by samthelion** [x0b/rcloneExplorer#5]
Hi, i've noticed that rcloneExplorer does not have http proxy support. Rclone itself has no flags to define proxy but supports it via environment variable. Would it be too much trouble to add http proxy support to rcloneExplorer?

Cheers!

**Comment by x0b** [comment]
Should be doable, but probably requires a bit of legwork because each and every rclone environment needs to be changed, and the settings entry for the proxy url.

We should probably implement both ```HTTP_PROXY```/```HTTPS_PROXY``` and ```NO_PROXY```.

**Comment by samthelion** [comment]
Sounds great! we should mark this issue as closed as soon as that's implemented. Thanks!

**Comment by x0b** [comment]
Proxy support will be included in the next version and can be tested in the current preview https://github.com/x0b/rcloneExplorer/releases/tag/v1.10.0-pre1.

This will only work for HTTP and HTTPS - other protocols need upstream support (e.g. FTP, SFTP, etc. is not sent over proxy).

**Comment by samthelion** [comment]
Well, i haven't tested it yet but since an option for proxy support is now included in settings i'm marking this issue as closed. Wether i'ts working or not that's a matter for another issue.

Cheers!
